### ISSUE TITLE
Project guidelines

### ISSUE THREAD

**Issue by jtojnar** [Heydon/Community-Icon-Font#1]
There should be some project guidelines for project participants to follow. This is important for visual consistence and easier glyph making.

For example:
- What should be glyph weight?
- Sharp or rounded edges?
- Which symbols should be associated with which characters?
- There should be baseline defined so when there are multiple icons in horizontal row it doesn't look weird
- Icons should also be fixed-width (monospace) for vertical rows (columns).

Also wouldn't it be better to save each glyph into its own file and generate the final font with some make script? I think for version management would be better. It could also automatize generating OTF, TTF etc.

**Comment by wyoumans** [comment]
huh?

**Comment by jtojnar** [comment]
Sorry, I discovered this repo in some blogpost and hadn't noticed how old this was. It's bad it didn't develop any more though.
